### ISSUE TITLE
macOS Sierra (Mail.app version 10) not supported

### ISSUE THREAD

**Issue by andreastt** [robertklep/quotefixformac#69]
After installing the add-on on macOS Sierra, an alert appears saying the bundle is not supported on Mail.app version 10 and to contact the author.

The bundle in _~/Library_ is subsequently deleted.

I have not yet investigated further.

**Comment by robertklep** [comment]
I'm not running Sierra myself, so can't offer a quick fix, but the first step to fixing this is usually to add the new Mail UUID to `QuoteFix.mailbundle/Contents/Info.plist`, as per [this FAQ](https://github.com/robertklep/quotefixformac/wiki/FAQ---Frequently-Asked-Questions#every-time-mac-os-x-updates-i-get-a-message-that-quotefix-is-disabled).

However, chances are that it still won't work, usually something breaks between major releases. I'll see if I can run Sierra in a VM.

**Comment by alvarnell** [comment]
Somebody else told me that MailPluginFix <http://code2k.net/products/mailpluginfix/> did not work for another Mail Plugin, so chances are that something changed.

-Al-

**Comment by atgmatt** [comment]
Unfortunately just updating the SupportedPluginCompatibilityUUIDs list to include the new PluginCompatibilityUUID from Mail doesn't seem to work.  I've tried it both through MailPluginFix and manually and in both cases Mail still complaints that the modified bundle isn't compatible with Mail 10.0

**Comment by robertklep** [comment]
I'll see if I can get a public beta to install in a VM so I can take a closer look, hopefully somewhere next week.

**Comment by robertklep** [comment]
First alpha release for Sierra support: [v2.8.0-alpha.1](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.1)

**Comment by andreastt** [comment]
@robertklep I can confirm that the alpha version works fine on macOS Sierra 10.12 Beta (16A239j).

Thanks so much! I tried your earlier suggestions, but I found the build system requirements and all the dependencies a bit much.

**Comment by atgmatt** [comment]
2.8.0-alpha.1 is working for me on macOS Sierra public beta 1.  Thanks, Robert!

**Comment by robertklep** [comment]
@andreastt @atgmatt thanks for testing!

I'll close this issue, if any other issues pop up, feel free to open a new one.

**Comment by atgmatt** [comment]
@robertklep Out of curiosity, what did you have to change to make it work?  There are a couple of other mail plugins I use heavily that don't work even after updating the Mail UUID, so I'm wondering if there's anything to learn from quotefix that might help the authors of those plugins.

**Comment by robertklep** [comment]
@atgmatt aside from having to add the new UUID (the procedure for which has changed slightly, see [this commit](https://github.com/robertklep/quotefixformac/commit/e5354de23d3b9c91ef285feaf045dab112cde25b)), the main issue was with some code that I added once to improve compatibility with another plugin (Attachment Tamer).

Since that plugin has been discontinued, it was easiest to just remove that code (in [this commit](https://github.com/robertklep/quotefixformac/commit/6f4e2cdc67e05ebd84d772065ae2d60bba27369f)) instead of trying to work out why it was failing on Sierra. That was basically the only change I had to make to get it up and working again, although there still remains an issue with the "remove attachment placeholders" feature that I still have to look in to.

**Comment by atgmatt** [comment]
I'll bet if I manually hack the configurations of the other plugins to add the UUID to the new Supported10.12PluginCompatibilityUUIDs instead of the old SupportedPluginCompatibilityUUIDs that they start working.  If so, I will report back to the others of those plugins.  This is a great find and will probably save some people a ton of time in porting their plugins.

**Comment by alvarnell** [comment]
I don’t know that it will help, but MailPluginFix <http://code2k.net/products/mailpluginfix/ <http://code2k.net/products/mailpluginfix/>> was updated recently, though I don’t know for certain that it includes the 10.12 fix or not.  Not a Sierra tester yet.

-Al-
