### ISSUE TITLE
strftime bug

### ISSUE THREAD

**Issue by LwsBtlr** [robertklep/quotefixformac#76]
With advanced templating the command `${message.sent.strftime("%H:%M` %Z")}` results in 14:54 %-0700 instead of the Time Zone name as specified in man strftime. %z returns "-0700" as expected.

(macOS Sierra 10.12.2)

**Comment by robertklep** [comment]
Good catch.

I apparently never implemented support for `%Z` (internally it gets treated as "Z", which in [Unicode date format patterns](http://unicode.org/reports/tr35/tr35-6.html#Date_Format_Patterns) translates to the timezone offset, which is what you're seeing).

Short term solution would be to use `zzz` instead of `%Z`, but I'll push a fix shortly as well.

**Comment by robertklep** [comment]
[v2.8.0-alpha.4](https://github.com/robertklep/quotefixformac/releases/tag/v2.8.0-alpha.4) should fix this.
